# Generated by Django 4.2 on 2023-08-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trial_quantity", models.PositiveIntegerField()),
                ("trial_bonus", models.PositiveIntegerField()),
                ("trial_access", models.CharField(max_length=10)),
                ("trial_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("beginner_quantity", models.PositiveIntegerField()),
                ("beginner_bonus", models.PositiveIntegerField()),
                ("beginner_access", models.CharField(max_length=10)),
                (
                    "beginner_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("advanced_quantity", models.PositiveIntegerField()),
                ("advanced_bonus", models.PositiveIntegerField()),
                ("advanced_access", models.CharField(max_length=10)),
                (
                    "advanced_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("expert_quantity", models.PositiveIntegerField()),
                ("expert_bonus", models.PositiveIntegerField()),
                ("expert_access", models.CharField(max_length=10)),
                ("expert_price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
